// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Health/status of the local database. */
	getAppStatus: () => typedError<AppStatus, string>(__TAURI_INVOKE("get_app_status")),
	/**  Liveness check. */
	ping: () => __TAURI_INVOKE<string>("ping"),
	/**
	 *  Scan `path`, grade + persist every prompt file, and return a summary.
	 *  Emits `scan-progress` per file and `scan-done` at the end.
	 */
	scanNow: (path: string) => typedError<ScanSummary, string>(__TAURI_INVOKE("scan_now", { path })),
	/**  Aggregated data for the Overview screen. */
	getOverview: () => typedError<Overview, string>(__TAURI_INVOKE("get_overview")),
	/**  Persist the folder to scan. */
	setScanFolder: (path: string) => typedError<null, string>(__TAURI_INVOKE("set_scan_folder", { path })),
	/**  The currently configured scan folder, if any. */
	getScanFolder: () => typedError<string | null, string>(__TAURI_INVOKE("get_scan_folder")),
	/**  Persist the scan schedule ("1h", "6h", "1d", "save", or "manual"). */
	setSchedule: (value: string) => typedError<null, string>(__TAURI_INVOKE("set_schedule", { value })),
	/**  The current scan schedule (defaults to "6h"). */
	getSchedule: () => typedError<string, string>(__TAURI_INVOKE("get_schedule")),
	/**  Toggle an alert ("regressions" or "digest"). */
	setAlert: (key: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_alert", { key, enabled })),
	/**  Whether an alert is on (defaults to on). */
	getAlert: (key: string) => typedError<boolean, string>(__TAURI_INVOKE("get_alert", { key })),
	/**  Every scanned file for the Prompts table. */
	listFiles: () => typedError<FileRow[], string>(__TAURI_INVOKE("list_files")),
	/**  One file's source + issues for the Detail screen. */
	getFileDetail: (fileId: string) => typedError<{
	id: string,
	name: string,
	project: string,
	path: string,
	grade: Grade,
	score: number,
	content: string,
	issues: IssueDetail[],
	/**  Score change since the previous scan of this file, if any. */
	delta: number | null,
} | null, string>(__TAURI_INVOKE("get_file_detail", { fileId })),
	/**  The weekly Scans digest. */
	getScansDigest: () => typedError<ScansDigest, string>(__TAURI_INVOKE("get_scans_digest")),
};

/* Types */
/**
 *  A small status payload proving the typed store ↔ frontend round-trip.
 * 
 *  Fields are `i32` so specta exports them as TS `number` (specta refuses to
 *  export 64-bit ints by default; our counts/versions are tiny).
 */
export type AppStatus = {
	schema_version: number,
	db_path: string,
	project_count: number,
	file_count: number,
};

/**  An item in the digest's "needs your eyes" list. */
export type DigestItem = {
	/**  "regressed" | "improved" | "new". */
	kind: string,
	file_id: string,
	title: string,
	detail: string,
};

/**  Everything the Detail screen needs for one file. */
export type FileDetail = {
	id: string,
	name: string,
	project: string,
	path: string,
	grade: Grade,
	score: number,
	content: string,
	issues: IssueDetail[],
	/**  Score change since the previous scan of this file, if any. */
	delta: number | null,
};

/**  A row in the Prompts table. */
export type FileRow = {
	id: string,
	name: string,
	project: string,
	grade: Grade,
	score: number,
	issue_count: number,
	modified: string | null,
};

/**  Letter grade. */
export type Grade = "A" | "B" | "C" | "D" | "F";

/**  One issue in the Detail view. */
export type IssueDetail = {
	line: number | null,
	severity: Severity,
	source: Source,
	title: string,
	why: string,
	fix_from: string | null,
	fix_to: string | null,
};

export type Overview = {
	has_data: boolean,
	scan_folder: string | null,
	overall_grade: Grade,
	overall_score: number,
	file_count: number,
	project_count: number,
	critical: number,
	warnings: number,
	nits: number,
	worklist: WorklistItem[],
	trend: number[],
	/**  Change across the trend window (latest − earliest). */
	trend_delta: number,
	/**  Most recent scan finish time (epoch seconds string). */
	last_scan: string | null,
};

/**  Summary of a completed scan, returned to the frontend. */
export type ScanSummary = {
	files_scanned: number,
	projects: number,
	critical: number,
	warnings: number,
	nits: number,
	overall_score: number,
	overall_grade: Grade,
};

/**  The weekly Scans digest. */
export type ScansDigest = {
	has_data: boolean,
	overall_grade: Grade,
	net_health: number,
	improved: number,
	regressed: number,
	scan_count: number,
	trend: number[],
	needs_attention: DigestItem[],
};

/**  Issue severity. */
export type Severity = 
/**  Critical. */
"hi" | 
/**  Warning. */
"mid" | 
/**  Nit. */
"lo";

/**  Where a rule's authority comes from (drives the source badge). */
export type Source = "anthropic" | "openai" | "karpathy" | "custom";

export type WorklistItem = {
	file_id: string,
	title: string,
	location: string,
	severity: Severity,
	source: Source,
	line: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

