// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Health/status of the local database. */
	getAppStatus: () => typedError<AppStatus, string>(__TAURI_INVOKE("get_app_status")),
	/**  Liveness check. */
	ping: () => __TAURI_INVOKE<string>("ping"),
};

/* Types */
/**
 *  A small status payload proving the typed store ↔ frontend round-trip.
 * 
 *  Fields are `i32` so specta exports them as TS `number` (specta refuses to
 *  export 64-bit ints by default; our counts/versions are tiny).
 */
export type AppStatus = {
	schema_version: number,
	db_path: string,
	project_count: number,
	file_count: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

