// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Health/status of the local database. */
	getAppStatus: () => typedError<AppStatus, string>(__TAURI_INVOKE("get_app_status")),
	/**  Liveness check. */
	ping: () => __TAURI_INVOKE<string>("ping"),
	/**
	 *  Scan everything, grade + persist every prompt file, and return a summary.
	 *  Emits `scan-phase`, `scan-progress` per file, and `scan-done` at the end.
	 */
	scanNow: () => typedError<ScanSummary, string>(__TAURI_INVOKE("scan_now")),
	/**  Aggregated data for the Overview screen. */
	getOverview: () => typedError<Overview, string>(__TAURI_INVOKE("get_overview")),
	/**  Persist the extra folders to scan on top of the harness's own projects. */
	setExtraScanFolders: (folders: string[]) => typedError<null, string>(__TAURI_INVOKE("set_extra_scan_folders", { folders })),
	/**  The extra folders currently configured (empty when none). */
	getExtraScanFolders: () => typedError<string[], string>(__TAURI_INVOKE("get_extra_scan_folders")),
	/**  Persist the scan schedule ("1h", "6h", "1d", "save", or "manual"). */
	setSchedule: (value: string) => typedError<null, string>(__TAURI_INVOKE("set_schedule", { value })),
	/**  The current scan schedule (defaults to "6h"). */
	getSchedule: () => typedError<string, string>(__TAURI_INVOKE("get_schedule")),
	/**  Toggle an alert ("regressions" or "digest"). */
	setAlert: (key: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_alert", { key, enabled })),
	/**  Whether an alert is on (defaults to on). */
	getAlert: (key: string) => typedError<boolean, string>(__TAURI_INVOKE("get_alert", { key })),
	/**
	 *  Enable/disable a built-in rule pack ("anthropic", "openai", "karpathy").
	 *  Toggles every rule of that source — affects grading on the next scan.
	 */
	setPack: (id: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_pack", { id, enabled })),
	/**  Whether every rule of a pack is enabled (defaults to on). */
	getPack: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("get_pack", { id })),
	/**  The built-in rules with their enabled state. */
	listRules: () => typedError<RuleInfo[], string>(__TAURI_INVOKE("list_rules")),
	/**  Enable/disable a single rule. */
	setRule: (id: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_rule", { id, enabled })),
	/**  Add a custom pattern rule (forbidden substring) with a severity. */
	addCustomRule: (title: string, pattern: string, severity: string) => typedError<null, string>(__TAURI_INVOKE("add_custom_rule", { title, pattern, severity })),
	/**  Add a natural-language custom rule (paid; evaluated by the AI provider). */
	addNlRule: (title: string, instruction: string, severity: string) => typedError<null, string>(__TAURI_INVOKE("add_nl_rule", { title, instruction, severity })),
	/**
	 *  Evaluate the built-in NL standards (free — needs only a configured
	 *  provider) plus, for licensed users, the custom NL rules. Persists
	 *  violations as issues and rescores the file (offer spec §5: the license
	 *  gates treatment, not diagnosis).
	 */
	evaluateNlRules: (fileId: string) => typedError<NlEvalResult, string>(__TAURI_INVOKE("evaluate_nl_rules", { fileId })),
	/**  Delete a custom rule. */
	deleteCustomRule: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_custom_rule", { id })),
	/**
	 *  Import a JSON pack file — an array of `{title, pattern, severity}` — as
	 *  custom rules. Returns how many were imported.
	 */
	importPack: (path: string) => typedError<number, string>(__TAURI_INVOKE("import_pack", { path })),
	/**  Save the AI provider config. An empty `api_key` keeps the stored one. */
	setAiConfig: (provider: string, apiKey: string, model: string) => typedError<null, string>(__TAURI_INVOKE("set_ai_config", { provider, apiKey, model })),
	/**  The current AI config (without the key). */
	getAiConfig: () => typedError<AiConfig, string>(__TAURI_INVOKE("get_ai_config")),
	/**  Verify the configured provider + key with a tiny request. */
	testAiConnection: () => typedError<string, string>(__TAURI_INVOKE("test_ai_connection")),
	/**  The current entitlement (whether the paid tier is unlocked). */
	getEntitlement: () => typedError<Entitlement, string>(__TAURI_INVOKE("get_entitlement")),
	/**
	 *  Validate and store a license key. Returns the unlocked plan, or an error if
	 *  the key isn't valid.
	 */
	setLicense: (key: string) => typedError<LicenseInfo, string>(__TAURI_INVOKE("set_license", { key })),
	/**  Remove the stored license, returning to the free tier. */
	clearLicense: () => typedError<null, string>(__TAURI_INVOKE("clear_license")),
	/**
	 *  Generate an AI rewrite for one issue of a file (paid). Returns a `from → to`
	 *  diff via the configured provider, replacing the static suggested fix.
	 */
	suggestFix: (fileId: string, issueIndex: number) => typedError<FixSuggestion, string>(__TAURI_INVOKE("suggest_fix", { fileId, issueIndex })),
	/**
	 *  Apply one or more fixes to a file (paid): snapshot the prior content into
	 *  `backups` (for undo), write the new content, and — if `commit` — stage and
	 *  commit it onto a `prompt-janitor/fix-*` branch. A failed commit rolls the
	 *  whole operation back so nothing is left half-applied.
	 */
	applyFix: (fileId: string, edits: FixEdit[], commit: boolean, origin: string) => typedError<ApplyResult, string>(__TAURI_INVOKE("apply_fix", { fileId, edits, commit, origin })),
	/**  Restore a file to its most recent pre-fix snapshot and drop that snapshot. */
	undoFix: (fileId: string) => typedError<null, string>(__TAURI_INVOKE("undo_fix", { fileId })),
	/**  Whether a file has a pre-fix snapshot available to undo. */
	hasBackup: (fileId: string) => typedError<boolean, string>(__TAURI_INVOKE("has_backup", { fileId })),
	/**  Every scanned file for the Prompts table. */
	listFiles: () => typedError<FileRow[], string>(__TAURI_INVOKE("list_files")),
	/**  Every project with its rolled-up counts and detected logo. */
	listProjects: () => typedError<ProjectRow[], string>(__TAURI_INVOKE("list_projects")),
	/**  One file's source + issues for the Detail screen. */
	getFileDetail: (fileId: string) => typedError<{
	id: string,
	name: string,
	project: string,
	path: string,
	grade: Grade,
	score: number,
	content: string,
	issues: IssueDetail[],
	/**  Score change since the previous scan of this file, if any. */
	delta: number | null,
	/**  Per-dimension scores, always length 5 in `Dimension::ALL` order. */
	dimensions: DimensionScore[],
} | null, string>(__TAURI_INVOKE("get_file_detail", { fileId })),
	/**
	 *  Everything the Analytics page needs, windowed to the trailing
	 *  `range_days`.
	 */
	getAnalytics: (rangeDays: number) => typedError<Analytics, string>(__TAURI_INVOKE("get_analytics", { rangeDays })),
	/**  The weekly Scans digest. */
	getScansDigest: () => typedError<ScansDigest, string>(__TAURI_INVOKE("get_scans_digest")),
	/**
	 *  Every starter template pack (#75): free to browse and preview — the
	 *  one-click write is the paid action, gated in `apply_template`.
	 */
	listTemplates: () => __TAURI_INVOKE<TemplateInfo[]>("list_templates"),
	/**
	 *  Write a starter template into `dest_dir` (paid). Never overwrites an
	 *  existing same-named file.
	 */
	applyTemplate: (templateId: string, destDir: string) => typedError<ApplyTemplateResult, string>(__TAURI_INVOKE("apply_template", { templateId, destDir })),
	/**
	 *  Everything the Setup screen renders: harnesses, the global layer, and each
	 *  project with its own artifacts.
	 */
	getSetup: () => typedError<SetupView, string>(__TAURI_INVOKE("get_setup")),
	/**  The rule files `harness` loads inside `project_path`, in load order. */
	getEffectiveRules: (harness: string, projectPath: string) => typedError<EffectiveRule[], string>(__TAURI_INVOKE("get_effective_rules", { harness, projectPath })),
	/**
	 *  Usage aggregates for the Analytics screen over the last `window_days`,
	 *  anchored to the current clock.
	 */
	getUsageOverview: (windowDays: number) => typedError<UsageOverview, string>(__TAURI_INVOKE("get_usage_overview", { windowDays })),
	/**
	 *  One project's usage over the last `window_days`, anchored to the current
	 *  clock: what `harness` invoked there, and how often it was worked in.
	 *  `window_days` is capped at a year — the daily series has a point per day.
	 */
	getProjectUsage: (harness: string, projectPath: string, windowDays: number) => typedError<ProjectUsage, string>(__TAURI_INVOKE("get_project_usage", { harness, projectPath, windowDays })),
	/**  Every harness we know of, detected or not. */
	listHarnesses: () => typedError<HarnessInfo[], string>(__TAURI_INVOKE("list_harnesses")),
	/**
	 *  Everything the menu-bar panel renders, anchored to the current clock (the
	 *  "sessions today" boundary is a UTC calendar day).
	 */
	getPanelSnapshot: () => typedError<PanelSnapshot, string>(__TAURI_INVOKE("get_panel_snapshot")),
	/**
	 *  Bring the main window forward on a given screen and close the panel.
	 * 
	 *  The panel is a separate window, so the route travels as an event the main
	 *  webview listens for rather than as a return value.
	 */
	openMain: (route: string, target: string | null) => __TAURI_INVOKE<void>("open_main", { route, target }),
	/**  Quit the app for real (the tray is the only other way out). */
	quit: () => __TAURI_INVOKE<void>("quit"),
	/**
	 *  Delete the local database and its settings, then come back up on a fresh
	 *  one so the app keeps working.
	 * 
	 *  The pooled connection is swapped for an in-memory database *before* the
	 *  files are listed and deleted: on Windows an open handle blocks the delete
	 *  outright, on macOS the old connection would keep writing WAL frames to a
	 *  file nobody is reading any more, and closing it is also what checkpoints
	 *  and removes `-wal`/`-shm` — so a list taken beforehand would over-count.
	 *  The fresh database is opened through the same [`store::init_db`] a cold
	 *  launch uses, so it is seeded identically.
	 * 
	 *  The confirmation is the command's own first step rather than the
	 *  webview's: a script that reached the page could otherwise skip a
	 *  JavaScript prompt by invoking the command directly. The dialog is native,
	 *  so the page cannot draw over it or answer it.
	 */
	resetAppData: () => typedError<string, string>(__TAURI_INVOKE("reset_app_data")),
	/**
	 *  Remove every trace of the app: the bundle first, then its data.
	 * 
	 *  Bundle first on purpose. Trashing can fail — a read-only volume, a
	 *  translocated copy, a permissions refusal — and a user whose app is still
	 *  installed should still have their database. Nothing destructive happens
	 *  until the bundle is safely in the Trash.
	 * 
	 *  A development build has no bundle to trash. It still clears its data (that
	 *  is the useful half in dev) and says what it did rather than pretending the
	 *  job is done; it is also the only path that returns to a still-running app.
	 * 
	 *  Confirmed natively first, for the same reason as [`reset_app_data`].
	 */
	uninstallApp: () => typedError<string, string>(__TAURI_INVOKE("uninstall_app")),
};

/* Types */
/**  Public view of the AI config (no secret key). */
export type AiConfig = {
	/**  A provider id from `provider::provider_ids()`, or "none". */
	provider: string,
	model: string,
	/**  Whether an API key is stored. */
	has_key: boolean,
};

/**
 *  Everything the Analytics page needs in one round trip (#88 data-viz
 *  epic). `issues_fixed_*` are lifetime totals (all of `fix_events`); every
 *  other field is a live snapshot except `trend`, which is windowed to the
 *  trailing `range_days`.
 */
export type Analytics = {
	overall_score: number,
	overall_grade: Grade,
	/**
	 *  Latest overall-history score minus the earliest within the window
	 *  (0 if the window has fewer than two points).
	 */
	overall_delta: number,
	files_tracked: number,
	project_count: number,
	issues_fixed_total: number,
	issues_fixed_auto: number,
	issues_fixed_manual: number,
	open_issues: number,
	open_critical: number,
	grade_distribution: GradeCount[],
	trend: TrendPoint[],
	common_issues: CommonIssue[],
};

/**
 *  A small status payload proving the typed store ↔ frontend round-trip.
 * 
 *  Fields are `i32` so specta exports them as TS `number` (specta refuses to
 *  export 64-bit ints by default; our counts/versions are tiny).
 */
export type AppStatus = {
	schema_version: number,
	db_path: string,
	project_count: number,
	file_count: number,
};

/**  The outcome of applying fixes. */
export type ApplyResult = {
	/**  The git branch the change was committed to, if the user opted in. */
	git_ref: string | null,
};

/**  Result of writing a template to disk. */
export type ApplyTemplateResult = {
	/**  The full path the template was written to. */
	path: string,
};

export type ArtifactKind = "rule" | "skill" | "agent" | "command" | "hook" | "mcp_server" | "plugin" | "settings";

/**
 *  An inventoried artifact, with its grade (when the file grader saw it) and
 *  its usage (when anything ever invoked it).
 */
export type ArtifactView = {
	id: number,
	harness: string,
	layer: Layer,
	kind: ArtifactKind,
	name: string,
	path: string,
	plugin_name: string | null,
	description: string | null,
	bytes: number,
	grade: string | null,
	score: number | null,
	file_id: string | null,
	usage: UsageStat | null,
};

/**
 *  One title from the "most common issues" leaderboard, with how many
 *  distinct files it appears in.
 */
export type CommonIssue = {
	title: string,
	files_affected: number,
};

/**  Top-level sessions started on one calendar day (`YYYY-MM-DD`, UTC). */
export type DayCount = {
	day: string,
	count: number,
};

/**  An item in the digest's "needs your eyes" list. */
export type DigestItem = {
	/**  "regressed" | "improved" | "new". */
	kind: string,
	file_id: string,
	title: string,
	detail: string,
};

/**  One dimension's rolled-up score for a file (drives the radar chart, #88). */
export type DimensionScore = {
	dimension: string,
	score: number,
};

/**  One rule file in the stack that applies to a project, in load order. */
export type EffectiveRule = {
	layer: Layer,
	path: string,
	name: string,
	grade: string | null,
	file_id: string | null,
};

/**  The current entitlement state (whether the paid tier is unlocked). */
export type Entitlement = {
	paid: boolean,
	email: string | null,
	plan: string | null,
};

/**  Everything the Detail screen needs for one file. */
export type FileDetail = {
	id: string,
	name: string,
	project: string,
	path: string,
	grade: Grade,
	score: number,
	content: string,
	issues: IssueDetail[],
	/**  Score change since the previous scan of this file, if any. */
	delta: number | null,
	/**  Per-dimension scores, always length 5 in `Dimension::ALL` order. */
	dimensions: DimensionScore[],
};

/**  A row in the Prompts table. */
export type FileRow = {
	id: string,
	name: string,
	/**
	 *  Absolute path on disk — lets the frontend match a freshly-written file
	 *  (e.g. an applied template) to its scanned id after a rescan.
	 */
	path: string,
	project: string,
	/**
	 *  Owning project's id (its absolute repo-root path) — used to group
	 *  files without colliding same-named projects.
	 */
	project_id: string,
	/**
	 *  File classification (e.g. `CLAUDE.md`, `AGENTS.md`, `.cursorrules`) —
	 *  drives the provider icon in the UI.
	 */
	kind: string,
	grade: Grade,
	score: number,
	issue_count: number,
	modified: string | null,
};

/**
 *  One edit: replace the first occurrence of `from` with `to`. An empty `from`
 *  appends `to` as a new trailing section (used for insertions).
 */
export type FixEdit = {
	from: string,
	to: string,
};

/**
 *  A provider-generated edit for one issue. `from` is an exact slice of the
 *  file to replace (empty for a pure insertion); `to` is the replacement.
 */
export type FixSuggestion = {
	from: string,
	to: string,
	note: string,
};

/**  Letter grade. */
export type Grade = "A" | "B" | "C" | "D" | "F";

/**
 *  One grade's share of `files_tracked`, always emitted for all five grades
 *  (zero-filled) so the Analytics distribution chart never has to guess at
 *  missing buckets.
 */
export type GradeCount = {
	grade: Grade,
	count: number,
};

/**  One installed agent harness and how much of it we know about. */
export type HarnessInfo = {
	id: string,
	display_name: string,
	detected: boolean,
	last_scan_at: string | null,
	project_count: number,
	/**  Top-level sessions only — sub-agent transcripts are not user sessions. */
	session_count: number,
};

export type InvocationKind = "skill" | "agent" | "mcp" | "builtin";

/**  One issue in the Detail view. */
export type IssueDetail = {
	line: number | null,
	severity: Severity,
	source: Source,
	title: string,
	why: string,
	fix_from: string | null,
	fix_to: string | null,
};

export type KindTotal = {
	kind: InvocationKind,
	total: number,
	avg_turn_tokens: number | null,
};

export type Layer = "global" | "project" | "plugin";

/**  What a valid license unlocks, shown in Settings. */
export type LicenseInfo = {
	email: string,
	plan: string,
};

/**
 *  Where the main window should land, emitted on the `navigate` event when a
 *  panel row is clicked. `target` is the row the screen should focus (a file
 *  id, an artifact kind), absent when the route alone is enough.
 */
export type NavigateEvent = {
	route: string,
	target: string | null,
};

/**  Result of an NL evaluation run: the verdicts plus the file's new score. */
export type NlEvalResult = {
	verdicts: NlVerdict[],
	score: number,
	grade: string,
};

/**  The provider's verdict on one NL rule for one file. */
export type NlVerdict = {
	rule_id: string,
	title: string,
	severity: string,
	source: string,
	violates: boolean,
	explanation: string,
};

export type Overview = {
	has_data: boolean,
	scan_folder: string | null,
	overall_grade: Grade,
	overall_score: number,
	file_count: number,
	project_count: number,
	critical: number,
	warnings: number,
	nits: number,
	worklist: WorklistItem[],
	trend: number[],
	/**  Change across the trend window (latest − earliest). */
	trend_delta: number,
	/**  Most recent scan finish time (epoch seconds string). */
	last_scan: string | null,
};

/**  One row of the panel's "fix these next" list. */
export type PanelFix = {
	/**  `files.id` — the absolute path, which is also the detail route's target. */
	file_id: string,
	/**  File basename, all the width the panel has. */
	name: string,
	project_name: string,
	grade: Grade,
	issue_count: number,
};

/**
 *  Everything the menu-bar panel renders in one payload.
 * 
 *  Scan state is deliberately absent: the panel subscribes to the
 *  `scan-phase` / `scan-progress` / `scan-done` events like the Setup screen
 *  does, and refetches this snapshot when a scan finishes.
 */
export type PanelSnapshot = {
	/**
	 *  False before the first scan — the panel shows "No scan yet" instead of
	 *  a verdict that would read as a perfect score.
	 */
	has_data: boolean,
	overall_grade: Grade,
	overall_score: number,
	/**  Change across the trend window (latest − earliest), from `get_overview`. */
	delta: number,
	/**
	 *  Newest of the harness and file scans, as RFC3339 — the shape every
	 *  other `last_scan_at` on the frontend is formatted from.
	 */
	last_scan_at: string | null,
	/**
	 *  At most three files that have issues, worst grade first then most
	 *  issues. Empty when there is nothing to fix.
	 */
	top_fixes: PanelFix[],
	/**
	 *  Skills the user authored — any layer but `plugin` — that no
	 *  invocation has ever resolved to. Plugin-bundled skills are excluded
	 *  on purpose: installing a plugin ships dozens the user never chose,
	 *  and counting them buries the handful they wrote and forgot.
	 */
	never_used_skills: number,
	/**  MCP servers whose rollup is at or above [`ERROR_RATE_THRESHOLD`]. */
	mcp_erroring: number,
	/**  Top-level sessions started since UTC midnight of `now_epoch_secs`. */
	sessions_today: number,
};

/**  A project rollup for the sidebar and the Prompts group headers. */
export type ProjectRow = {
	id: string,
	name: string,
	grade: Grade,
	score: number,
	file_count: number,
	issue_count: number,
	/**  Base64 `data:` URI of the project's logo, if one was detected. */
	logo: string | null,
	/**  Most recent file mtime in the project (epoch seconds string). */
	modified: string | null,
	/**  The harness that has worked here most, when any has. */
	harness: string | null,
	/**  Top-level sessions that harness has run here (all time). */
	session_count: number,
	last_session_at: string | null,
	/**
	 *  Invocable artifacts configured in the project (skill/agent/command/
	 *  mcp_server) that nothing has ever invoked.
	 */
	never_used_count: number,
	/**
	 *  Those of them whose rollup says at least a quarter of their calls
	 *  errored.
	 */
	error_count: number,
	/**
	 *  False only when a harness has seen the directory and it is gone from
	 *  disk — a project no harness knows about is assumed to be there.
	 */
	exists: boolean,
};

export type ProjectSessions = {
	path: string,
	name: string,
	sessions: number,
};

/**  A project the harness has seen, and everything configured inside it. */
export type ProjectSetup = {
	harness: string,
	path: string,
	/**  Last path component — what the UI labels the project with. */
	name: string,
	exists: boolean,
	session_count: number,
	last_session_at: string | null,
	artifacts: ArtifactView[],
};

/**
 *  What one project's usage tab renders, over the same window as the
 *  Analytics overview.
 */
export type ProjectUsage = {
	/**
	 *  Every `(kind, target)` invoked inside the project, busiest first.
	 *  Sub-agent invocations count — they ran in this project's sessions.
	 */
	ranked: RankedTarget[],
	/**
	 *  Top-level sessions per day, oldest day first — the activity sparkline.
	 *  Zero-filled: one point per day of the window, so a quiet day is a zero
	 *  the chart can draw rather than a gap it would interpolate across.
	 */
	sessions_per_day: DayCount[],
};

/**
 *  One invoked target over the reporting window — the row the ranked usage
 *  lists render.
 */
export type RankedTarget = {
	kind: InvocationKind,
	target: string,
	/**
	 *  The artifact the target resolved to, when it resolved to one at all —
	 *  builtins and unlinked targets have none.
	 */
	artifact_id: number | null,
	uses: number,
	/**  Distinct sessions the target was invoked in (sub-agent sessions count). */
	sessions: number,
	/**  Share of invocations that returned an error, 0–1. */
	error_rate: number | null,
	/**  Mean context tokens per turn, over the turns that recorded any. */
	avg_turn_tokens: number | null,
};

/**  A rule (built-in or custom) with its current enabled state. */
export type RuleInfo = {
	id: string,
	title: string,
	description: string,
	source: Source,
	severity: Severity,
	enabled: boolean,
	/**  True for user-created custom rules (deletable). */
	custom: boolean,
	/**  True for natural-language rules evaluated by the AI provider. */
	nl: boolean,
	/**  The forbidden substring (pattern rules) or the instruction (NL rules). */
	pattern: string | null,
	/**
	 *  Open issues this rule is currently responsible for — dismissed ones
	 *  stop counting, so silencing a finding silences the number too.
	 */
	hit_count: number,
};

/**  Summary of a completed scan, returned to the frontend. */
export type ScanSummary = {
	files_scanned: number,
	projects: number,
	critical: number,
	warnings: number,
	nits: number,
	overall_score: number,
	overall_grade: Grade,
};

/**  The weekly Scans digest. */
export type ScansDigest = {
	has_data: boolean,
	overall_grade: Grade,
	net_health: number,
	improved: number,
	regressed: number,
	scan_count: number,
	trend: number[],
	needs_attention: DigestItem[],
	/**
	 *  Log lines the latest scan's harness pass could not parse, summed over
	 *  every harness that reported. Zero is the normal case; a non-zero count
	 *  is the honest caveat on the usage numbers.
	 */
	skipped_lines: number,
};

/**  Everything the Setup screen renders in one round trip. */
export type SetupView = {
	harnesses: HarnessInfo[],
	/**  Global + plugin layers: the artifacts that apply everywhere. */
	global: ArtifactView[],
	projects: ProjectSetup[],
};

/**  Issue severity. */
export type Severity = 
/**  Critical. */
"hi" | 
/**  Warning. */
"mid" | 
/**  Nit. */
"lo";

/**  Where a rule's authority comes from (drives the source badge). */
export type Source = "anthropic" | "openai" | "cursor" | "karpathy" | "custom";

export type TargetRate = {
	target: string,
	total: number,
	error_rate: number | null,
};

/**  One starter template: metadata plus its full content for the free preview. */
export type TemplateInfo = {
	id: string,
	/**  Stack id: `react-ts`, `python`, or `rust`. */
	stack: string,
	/**  The instruction file name this template produces: `CLAUDE.md` or `AGENTS.md`. */
	file_type: string,
	title: string,
	description: string,
	/**
	 *  The full file content — shown as a free, honest preview even though
	 *  writing it to disk is a paid action.
	 */
	preview: string,
};

/**  One point on the Analytics overall-score trend line. */
export type TrendPoint = {
	/**  Epoch-seconds string (matches `grade_history.recorded_at`). */
	t: string,
	score: number,
};

/**
 *  What the Analytics usage tab renders. Every aggregate is bounded by the
 *  same `window_days`, so the four of them always describe one period.
 */
export type UsageOverview = {
	/**
	 *  The window every aggregate below was computed over, echoed back so the
	 *  UI can label what it is showing.
	 */
	window_days: number,
	/**  Every `(kind, target)` invoked in the window, busiest first. */
	ranked: RankedTarget[],
	/**
	 *  Totals per invocation kind in `skill, agent, mcp, builtin` order —
	 *  always four rows, zeroed for a kind the window holds nothing of.
	 */
	by_kind: KindTotal[],
	/**  Top-level sessions started in the window, per project. */
	sessions_per_project: ProjectSessions[],
	/**  Error rate per MCP server over the window, busiest first. */
	mcp_error_rates: TargetRate[],
};

/**  The rollup row for one artifact (`usage_stats`). */
export type UsageStat = {
	total: number,
	sessions: number,
	last_used: string | null,
	error_rate: number | null,
	avg_turn_tokens: number | null,
	count_30d: number,
	count_prev_30d: number,
};

export type WorklistItem = {
	file_id: string,
	title: string,
	location: string,
	severity: Severity,
	source: Source,
	line: number | null,
	/**  Containing project (for the "By project" grouping). */
	project: string,
	/**  File last-modified epoch string (for the "Newest" grouping). */
	modified: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

