//! System tray icon + menu (the menu-bar presence).
//!
//! Left-click toggles the floating panel under the icon; right-click keeps the
//! native menu for the quick actions the panel does not cover.

use tauri::menu::MenuBuilder;
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::App;

use crate::{panel, window_policy};

/// The menu-bar icon, as a macOS *template* image: black ink plus alpha, which
/// the system tints for the light bar, the dark bar and the clicked state.
///
/// `default_window_icon()` — the full-colour app icon — is what a tray icon
/// must not be: macOS shows a status-item image verbatim, so the app's rounded
/// blue tile arrives as a blue square.
///
/// Generated by `icons/tray/scripts/make_tray_icon.py`, and authored on an
/// 18 pt canvas because that is the only size that survives: `tray-icon`
/// re-encodes the image and pins the `NSImage` to `icon_height = 18.0`
/// (`platform_impl/macos/mod.rs`), scaling the width to match. Art drawn on the
/// nominal 22 pt status-item canvas is therefore letterboxed down — its ink
/// lands around 13 pt, visibly smaller than its neighbours in the bar. One
/// density is shipped: `NSImage` is handed these bytes once and asked for 18 pt,
/// so 36 px is the Retina raster and AppKit down-samples it for a 1x bar.
const TRAY_ICON: &[u8] = include_bytes!("../icons/tray/trayTemplate@2x.png");

/// Build and install the tray icon. Call once at startup.
pub fn setup(app: &App) -> tauri::Result<()> {
    let menu = MenuBuilder::new(app)
        .text("open", "Open Prompt Janitor")
        .text("scan", "Scan now")
        .separator()
        .text("quit", "Quit")
        .build()?;

    let mut builder = TrayIconBuilder::new()
        .tooltip("Prompt Janitor")
        // macOS-only in effect, harmless elsewhere: without it the template
        // art renders as flat black and disappears on a dark menu bar.
        .icon_as_template(true)
        .menu(&menu)
        .show_menu_on_left_click(false)
        .on_menu_event(|app, event| match event.id().as_ref() {
            "open" => window_policy::show_main(app),
            "scan" => {
                let app = app.clone();
                tauri::async_runtime::spawn(async move {
                    crate::commands::scan_everything(&app);
                });
            }
            "quit" => app.exit(0),
            _ => {}
        })
        .on_tray_icon_event(|tray, event| {
            // Only the release of a left-click: the press half of the same
            // click would toggle the panel straight back shut.
            if let TrayIconEvent::Click {
                button: MouseButton::Left,
                button_state: MouseButtonState::Up,
                rect,
                ..
            } = event
            {
                panel::toggle(tray.app_handle(), rect);
            }
        });

    match tauri::image::Image::from_bytes(TRAY_ICON) {
        Ok(icon) => builder = builder.icon(icon),
        // An unreadable icon is not worth losing the menu bar over: the tray
        // still builds, with whatever default the platform gives it.
        Err(error) => eprintln!("tray: could not decode the template icon: {error}"),
    }

    builder.build(app)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The bytes are compiled in, so a bad file is a shipped bug rather than a
    /// startup one: decode them here, where a test can see it.
    #[test]
    fn the_template_icon_decodes_at_36_px() {
        let icon = tauri::image::Image::from_bytes(TRAY_ICON).expect("tray icon should decode");
        // 18 pt at 2x. A square icon matters as much as its size: tray-icon
        // derives the width from the height, so a non-square raster would be
        // stretched rather than letterboxed.
        assert_eq!((icon.width(), icon.height()), (36, 36));
    }
}
