//! System tray icon + menu (the menu-bar presence).
//!
//! Left-click toggles the floating panel under the icon; right-click keeps the
//! native menu for the quick actions the panel does not cover.

use tauri::menu::MenuBuilder;
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::App;

use crate::{panel, window_policy};

/// The menu-bar icon, as a macOS *template* image: black ink plus alpha, which
/// the system tints for the light bar, the dark bar and the clicked state.
///
/// `default_window_icon()` — the full-colour app icon — is what a tray icon
/// must not be: macOS scales it to the bar and shows it verbatim, so the app's
/// rounded blue tile arrives as a blue square. Generated by
/// `icons/tray/scripts/make_tray_icon.py`; the `@2x` art is included because
/// tao hands the bytes straight to `NSImage`, which reads the alpha channel at
/// whatever density the display has and down-samples the 44 px art cleanly on a
/// 1x screen.
const TRAY_ICON: &[u8] = include_bytes!("../icons/tray/trayTemplate@2x.png");

/// Build and install the tray icon. Call once at startup.
pub fn setup(app: &App) -> tauri::Result<()> {
    let menu = MenuBuilder::new(app)
        .text("open", "Open Prompt Janitor")
        .text("scan", "Scan now")
        .separator()
        .text("quit", "Quit")
        .build()?;

    let mut builder = TrayIconBuilder::new()
        .tooltip("Prompt Janitor")
        // macOS-only in effect, harmless elsewhere: without it the template
        // art renders as flat black and disappears on a dark menu bar.
        .icon_as_template(true)
        .menu(&menu)
        .show_menu_on_left_click(false)
        .on_menu_event(|app, event| match event.id().as_ref() {
            "open" => window_policy::show_main(app),
            "scan" => {
                let app = app.clone();
                tauri::async_runtime::spawn(async move {
                    crate::commands::scan_everything(&app);
                });
            }
            "quit" => app.exit(0),
            _ => {}
        })
        .on_tray_icon_event(|tray, event| {
            // Only the release of a left-click: the press half of the same
            // click would toggle the panel straight back shut.
            if let TrayIconEvent::Click {
                button: MouseButton::Left,
                button_state: MouseButtonState::Up,
                rect,
                ..
            } = event
            {
                panel::toggle(tray.app_handle(), rect);
            }
        });

    match tauri::image::Image::from_bytes(TRAY_ICON) {
        Ok(icon) => builder = builder.icon(icon),
        // An unreadable icon is not worth losing the menu bar over: the tray
        // still builds, with whatever default the platform gives it.
        Err(error) => eprintln!("tray: could not decode the template icon: {error}"),
    }

    builder.build(app)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The bytes are compiled in, so a bad file is a shipped bug rather than a
    /// startup one: decode them here, where a test can see it.
    #[test]
    fn the_template_icon_decodes_at_44_px() {
        let icon = tauri::image::Image::from_bytes(TRAY_ICON).expect("tray icon should decode");
        assert_eq!((icon.width(), icon.height()), (44, 44));
    }
}
